### ISSUE TITLE
Wishlist no longer exists

### ISSUE THREAD

**Issue by SamWhited** [xlcollaborative/xlcollaborative.com#1]
There are broken links to the "wishlist" in several places, including in the text of the agreement. I didn't want to submit a PR simply removing these links since it was in the document itself in case it was just temporarily down, but am happy to do so if it's no longer in use.

**Comment by kemitchell** [comment]
Thanks for letting me know! I thought I had a link checker running on that age, but apparently either I do not, or it isn't working anymore.

**Comment by kemitchell** [comment]
Thanks again for your issue, @SamWhited. I've just moved the wishlist page, which had gone down, to https://xlcollaborative.com/wishlist. I've restyled the links to stand out a bit more from the text.
